FROM maven:3.9.4-eclipse-temurin-17

USER root

# Install Docker CLI and Compose plugin
RUN apt-get update && \
    apt-get install -y curl gnupg lsb-release ca-certificates && \
    curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker.gpg && \
    echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker.gpg] https://download.docker.com/linux/debian bookworm stable" > /etc/apt/sources.list.d/docker.list && \
    apt-get update && \
    apt-get install -y docker-ce-cli docker-compose-plugin && \
    apt-get clean

# Optional: Add a user or groups if needed
# RUN groupadd docker && usermod -aG docker jenkins

USER root
